spring.application.name=NBCC-Auth

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/restaurantreservation}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devJPA}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

server.port=${PORT:8082}

logging.level.root=INFO
logging.level.nbcc=${APP_LOG_LEVEL:info}

jwt.issuer=${JWT_ISSUER:Flavor-da-Casa}
jwt.timeout=${JWT_TIMEOUT:3600}

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:nbcc}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:false}

email.from=${EMAIL_FROM:noreply@flavordacasa.ca}

jwt.private-key-location=classpath:keys/private_key.pem
jwt.public-key-location=classpath:keys/public_key.pem
