spring.application.name=Restaurant-Reservation

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/restaurantreservation}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devJPA}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

server.port=${PORT:8080}
server.servlet.session.persistent=false

logging.level.root=info
logging.level.org.springframework.web=info
logging.level.nbcc=${APP_LOG_LEVEL:info}

spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:false}

auth.rest.api.url=${AUTH_REST_API_URL:http://localhost}
auth.rest.api.port=${AUTH_REST_API_PORT:8082}

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:nbcc}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:false}

email.from=${EMAIL_FROM:noreply@flavordacasa.ca}
